### ISSUE TITLE
Reproducibility Issue

### ISSUE THREAD

**Issue by jorshi** [turian/torchsynth#248]
If you received an Error or Warning regarding reproducibility while using torchsynth please leave a comment here with details about your CPU architecture and what random results you got.

**Comment by turian** [comment]
@jorshi do you think we should have this in github discussions?

**Comment by jorshi** [comment]
@turian -- ya I like that idea.

**Comment by turian** [comment]
We will create a discussion and add this to the docs.

**Comment by turian** [comment]
https://github.com/turian/torchsynth/discussions/293
